import { Router } from 'express';
import rateLimit from 'express-rate-limit';
import { listResources, listOwnedProperties, listTenantApplications, getResource, createResource, updateResource, deleteResource, changeStatus } from '../controllers/resourceController.js';
import { authenticate } from '../middleware/auth.js';
import { requireCapabilityPermission } from '../middleware/rolePermission.js';
import { acceptTenantInvitation, createTenantInvitation, resendTenantInvitation, listLandlordTenants, cancelTenantInvitation } from '../controllers/tenantInvitationController.js';
const router = Router();
const tenantInvitationLimiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 12, standardHeaders: true, legacyHeaders: false });
router.use(authenticate);
router.get('/properties/mine', listOwnedProperties);
router.get('/applications/mine', listTenantApplications);
router.get('/tenant-invitations/workspace', requireCapabilityPermission('landlord', 'resource:tenants', 'view'), listLandlordTenants);
router.post('/tenant-invitations', tenantInvitationLimiter, requireCapabilityPermission('landlord', 'resource:tenants', 'create'), createTenantInvitation);
router.post('/tenant-invitations/:id/resend', tenantInvitationLimiter, requireCapabilityPermission('landlord', 'resource:tenants', 'edit'), resendTenantInvitation);
router.post('/tenant-invitations/:id/cancel', requireCapabilityPermission('landlord', 'resource:tenants', 'edit'), cancelTenantInvitation);
router.post('/tenant-invitations/accept', acceptTenantInvitation);
router.get('/:resource', listResources);
router.post('/:resource', createResource);
router.get('/:resource/:id', getResource);
router.patch('/:resource/:id', updateResource);
router.delete('/:resource/:id', deleteResource);
router.post('/:resource/:id/status', changeStatus);
export default router;
